### ISSUE TITLE
Suppor dns or pastebin?

### ISSUE THREAD

**Issue by Dazmed707** [HamedMasafi/qt-rat#5]
In make client..

does it support dns connection instead of ip?
or pastebin instead of ip?

**Comment by HamedMasafi** [comment]
What does the "dns connection" or "pastebin" mean?

**Comment by Dazmed707** [comment]
en lugar de escribir 127.0.0.1

dns: ejemplo.ddns.net
con no-ip.com

o pastebin

pastebin: https://pastebin.com/raw/TdhQ682N

patebin usa LimeRat

https://github.com/NYAN-x-CAT/Lime-RAT

**Comment by HamedMasafi** [comment]
No, there is no support of them
