### ISSUE TITLE
Erro clien execute

### ISSUE THREAD

**Issue by Dazmed707** [HamedMasafi/qt-rat#6]
Win10 error execute client

![image](https://user-images.githubusercontent.com/35184132/104883495-da431b80-5932-11eb-8e9a-915c5ffddb78.png)

VCRUNTIME140.dll
not found

**Comment by HamedMasafi** [comment]
You can build client with static runtimes

**Comment by Dazmed707** [comment]
how do I do that ..

where is that option

**Comment by HamedMasafi** [comment]
First, build Qt in static mode

**Comment by Dazmed707** [comment]
You send me qt-rat compiled

I not compiled
